### ISSUE TITLE
Program/Curriculum Section Student Page

### ISSUE THREAD

**Issue by SamuelRUM** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#131]
A new section (could be a new route inside of student page) that houses your program/curriculum in a table similar to the PDF we all get. However the data here should be available in the database so that other things can make reference to certain programs such as the suggestion algorithm. Bonus: in this table, clearly show (with highlight or something else) what courses the student has taken and which they are missing (modifier 3).

**Comment by CarlosRodriguez260** [comment]
Created a new page that displays all the courses a student must take in order to graduate from their current program. The tables display the courses a student is recommended to take on a given year and semester, as well as pre-requisites needed to take certain courses. 

This was implemented in branch #139 .
