### ISSUE TITLE
Complete curriculum in student page

### ISSUE THREAD

**Issue by ChristianMorales25** [uprm-inso4101-2023-2024-s2/semester-project-studentenrollmentsystem#72]
- [x] Display what year and semester the curriculum data is showing to student
- [x] Display the student's classes in their weekly schedule table
- [x] Ability for student to switch between data of different semesters
- [x] Redo button layout for moving between different semesters

**Comment by CarlosRodriguez260** [comment]
Implemented schedule table on student page, which works dynamically with csv files containing information of a student's courses in a semester and displays their courses in a more graphical manner. Implemented way so that student page lets you know what year and semester of data is being shown to student, the ability for student to switch between semesters with buttons and tidied up the button layout to look better.
